src/objects/Incident_Report__c.object
<CustomObject>
    <fields>
        <fullName>Affected_Data_Centers__c</fullName>
        <label>Affected Data Centers</label>
        <picklist>
            <picklistValues>
                <fullName>US1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EU1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDN</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Affected_Accounts__c</fullName>
        <label>Number of Affected Accounts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RaaS_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>RaaS Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Incident Report</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>AutoId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IR_Email__c.object
<CustomObject>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>IR Emails</relationshipLabel>
        <relationshipName>IR_Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IR Email</label>
    <nameField>
        <label>IR Email Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IR Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IR_EmailTriggerTest.cls
@isTest(SeeAllData=true) //This annotation requires API v24 or greater
public class IR_EmailTriggerTest {
    @isTest
    static void testTrigger() {
        Test.setMock(HttpCalloutMock.class, new IR_MarketoClientMock()); 
        
        Test.startTest();
        Incident_Report__c incident = new Incident_Report__c();       
        incident.Affected_Data_Centers__c = 'US;EU;AU';
        incident.RaaS_Failure_Rate__c = '10';
        incident.Name = 'Unit Test Incident';
        incident.Start_Time__c = Date.today();
        insert incident;
        
        IR_Email__c email = new IR_Email__c();
        email.Name = 'Unit Test Email';
        email.Incident_Report__c = incident.Id;
        email.Email_Body__c = 'Unit Test Body';
        insert email;
        Test.stopTest();
        Incident_Report__c updatedRecord = [SELECT Number_of_Affected_Accounts__c 
                                                  FROM Incident_Report__c 
                                                  WHERE Incident_Report__c.Id = :incident.Id];
        Integer affectedActual = Integer.valueOf(updatedRecord.Number_of_Affected_Accounts__c);
        Integer affectedExpected = 0;
        System.assertNotEquals(affectedExpected, affectedActual);
    }
}