src/objects/Incident_Report__c.object
<CustomObject>
    <label>Incident Report</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>AutoId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IR_Email__c.object
<CustomObject>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>IR Emails</relationshipLabel>
        <relationshipName>IR_Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IR Email</label>
    <nameField>
        <label>IR Email Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IR Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IR_Dispatch.cls
// The philosophy here is to limit the amount of time on the trigger as much as possible, 
// and get the work broken out into a Batchable class like IR_MarketoBatch
public class IR_Dispatch {
    public static void enqueueJob(IR_Email__c[] emails) {
        for(IR_Email__c e :emails) {
            // There should be no conceivable way for more 
            // than one Incident Report to get returned by this query
            Incident_Report__c i = [SELECT Id FROM Incident_Report__c WHERE id = :e.Incident_Report__c];
            System.debug('Found Incident Id:' + i.Id);
            
            // This calls the .execute() method of IR_MarketoClient
            //System.enqueueJob(new IR_MarketoClient(i, e));
            
            // Use Batch method instead
            IR_MarketoBatch batch = new IR_MarketoBatch(i.Id, e.Id);
        	Database.executeBatch(batch);
        }
    }
}