src/objects/Incident_Report__c.object
<CustomObject>
    <fields>
        <fullName>Affected_Data_Centers__c</fullName>
        <label>Affected Data Centers</label>
        <picklist>
            <picklistValues>
                <fullName>US1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EU1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDN</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Chat_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Chat Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Comments Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Time_to_Resolution__c</fullName>
        <label>Estimated Time to Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>15 minutes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 minutes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45 minutes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 minutes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Feed_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Feed Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gamification_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Gamification Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Identity_Store_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Identity Store Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Login_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Login Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RaaS_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>RaaS Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>P0 - Outage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P1 - Interruption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2 - Degradation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3 - Degradation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Share_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Share Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Webhooks_Failure_Rate__c</fullName>
        <globalPicklist>Failure_Rates</globalPicklist>
        <label>Webhooks Failure Rate</label>
        <type>Picklist</type>
    </fields>
    <label>Incident Report</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>AutoId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IR_Email__c.object
<CustomObject>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>IR Emails</relationshipLabel>
        <relationshipName>IR_Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Mortem</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IR Email</label>
    <nameField>
        <label>IR Email Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IR Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IR_SendUpdate.cls
public class IR_SendUpdate {

    private final Incident_Report__c report;
	public String updateText{get;set;}
    
    public IR_SendUpdate() {
        report = [SELECT Id, 
                          Name,  
                          Affected_Data_Centers__c,
                          Description__c,
                          Start_Time__c,
                          End_Time__c,
                          Severity__c,
                          Estimated_Time_to_Resolution__c,
                          Chat_Failure_Rate__c,
                          Comments_Failure_Rate__c,
                          Feed_Failure_Rate__c,
                          Gamification_Failure_Rate__c,
                          Identity_Store_Failure_Rate__c,
                          Login_Failure_Rate__c,
                          RaaS_Failure_Rate__c,
                          Share_Failure_Rate__c,
                          Webhooks_Failure_Rate__c
                          FROM Incident_Report__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
    }

    public Incident_Report__c getReport() {
        return report;
    }
    
    public String getEmailBodyText() {
        String body = 'We would like to provide the following update regarding the current service interruption:  \n\n' +
          updateText + '\n\n' +
          'Event start date and time: ' + report.Start_Time__c + '\n\n' +
          'Data center(s) impacted: ' + report.Affected_Data_Centers__c + '\n\n' +
          'Current status: Open \n\n' +
          'Impacted APIs: \n';
        if(report.Chat_Failure_Rate__c != '0%' && report.Chat_Failure_Rate__c != null) 
            body += 'Chat: ' + report.Chat_Failure_Rate__c + ' failure rate\n';
        if(report.Comments_Failure_Rate__c != '0%' && report.Comments_Failure_Rate__c != null) 
            body += 'Comments: ' + report.Comments_Failure_Rate__c +' failure rate\n';
        if(report.Feed_Failure_Rate__c != '0%' && report.Feed_Failure_Rate__c != null) 
            body += 'Feed: ' + report.Feed_Failure_Rate__c + ' failure rate\n';
        if(report.Gamification_Failure_Rate__c != '0%' && report.Gamification_Failure_Rate__c != null) 
            body += 'Game Mechanics: ' + report.Gamification_Failure_Rate__c + ' failure rate\n';
        if(report.Identity_Store_Failure_Rate__c != '0%' && report.Identity_Store_Failure_Rate__c != null) 
            body += 'Identity Store: ' + report.Identity_Store_Failure_Rate__c + ' failure rate\n';
        if(report.Login_Failure_Rate__c != '0%' && report.Login_Failure_Rate__c != null) 
            body += 'Social Login: ' + report.Login_Failure_Rate__c + ' failure rate\n';
        if(report.RaaS_Failure_Rate__c != '0%' && report.RaaS_Failure_Rate__c != null) 
            body += 'RaaS: ' + report.RaaS_Failure_Rate__c  + ' failure rate\n';
        if(report.Share_Failure_Rate__c != '0%' && report.Share_Failure_Rate__c != null) 
            body += 'Social Share: ' + report.Share_Failure_Rate__c + ' failure rate\n';
        if(report.Webhooks_Failure_Rate__c != '0%' && report.Webhooks_Failure_Rate__c != null) 
            body += 'Webhooks: ' + report.Webhooks_Failure_Rate__c + ' failure rate\n';
        
        return body;
    }

    public PageReference save() {
        // CREATE UPDATE
    	IR_Email__c updateEmail = new IR_Email__c();
    
        // POPULATE IT FROM THE incident
        updateEmail.Incident_Report__c = report.Id;
        updateEmail.Type__c = 'Update';
        updateEmail.Name = 'Update Notification of Gigya Service Interruption on ' + report.Start_Time__c;
        updateEmail.Email_Body__c = getEmailBodyText();
        
        System.debug('********SENDING UPDATE EMAIL***********');
        insert updateEmail;
        
        PageReference reportPage = new ApexPages.StandardController(report).view();
        reportPage.setRedirect(true);
        return reportPage;
    }
}